import { Category } from "./types";

export const categories: Category[] = [
  {
    slug: "cars",
    name: "سيارات",
    description: "سيارات جديدة ومستعملة بجميع الفئات",
    icon: "🚗",
    image: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=600&h=400&fit=crop",
    productCount: 156,
    subcategories: [
      { slug: "sedan", name: "سيدان", icon: "🚗", productCount: 45 },
      { slug: "suv", name: "دفع رباعي", icon: "🚙", productCount: 38 },
      { slug: "pickup", name: "بيك أب", icon: "🛻", productCount: 25 },
      { slug: "sports", name: "رياضية", icon: "🏎️", productCount: 12 },
      { slug: "electric", name: "كهربائية", icon: "⚡", productCount: 8 },
      { slug: "used-cars", name: "مستعملة", icon: "🔄", productCount: 28 },
    ],
  },
  {
    slug: "auto-parts",
    name: "قطع غيار السيارات",
    description: "قطع غيار أصلية ومتقنة لجميع أنواع السيارات",
    icon: "🔧",
    image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600&h=400&fit=crop",
    productCount: 423,
    subcategories: [
      { slug: "brakes", name: "فرامل", icon: "🛞", productCount: 85 },
      { slug: "engine", name: "محرك", icon: "⚙️", productCount: 120 },
      { slug: "oil-filters", name: "زيوت وفلاتر", icon: "🛢️", productCount: 95 },
      { slug: "tires", name: "إطارات", icon: "⭕", productCount: 65 },
      { slug: "batteries", name: "بطاريات", icon: "🔋", productCount: 30 },
      { slug: "lights", name: "إضاءة", icon: "💡", productCount: 28 },
    ],
  },
  {
    slug: "clothing",
    name: "ملابس",
    description: "ملابس رجالية ونسائية وأطفال عصرية",
    icon: "👕",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600&h=400&fit=crop",
    productCount: 892,
    subcategories: [
      { slug: "men", name: "رجالي", icon: "👔", productCount: 320 },
      { slug: "women", name: "نسائي", icon: "👗", productCount: 380 },
      { slug: "kids", name: "أطفال", icon: "👶", productCount: 150 },
      { slug: "thobes", name: "ثياب", icon: "🧕", productCount: 42 },
    ],
  },
  {
    slug: "building-materials",
    name: "مواد بناء",
    description: "كل ما تحتاجه لأعمال البناء والتشطيب",
    icon: "🧱",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop",
    productCount: 267,
    subcategories: [
      { slug: "cement", name: "أسمنت", icon: "🧱", productCount: 45 },
      { slug: "steel", name: "حديد", icon: "🔩", productCount: 60 },
      { slug: "tiles", name: "بلاط وسيراميك", icon: "🔲", productCount: 85 },
      { slug: "paint", name: "دهانات", icon: "🎨", productCount: 42 },
      { slug: "plumbing", name: "سباكة", icon: "🔧", productCount: 35 },
    ],
  },
  {
    slug: "accessories",
    name: "إكسسوارات",
    description: "إكسسوارات عصرية للمنزل والسيارة والمزيد",
    icon: "💎",
    image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&h=400&fit=crop",
    productCount: 534,
    subcategories: [
      { slug: "watches", name: "ساعات", icon: "⌚", productCount: 120 },
      { slug: "sunglasses", name: "نظارات شمسية", icon: "🕶️", productCount: 85 },
      { slug: "bags", name: "حقائب", icon: "👜", productCount: 150 },
      { slug: "wallets", name: "محافظ", icon: "👛", productCount: 95 },
      { slug: "jewelry", name: "مجوهرات", icon: "💍", productCount: 84 },
    ],
  },
  {
    slug: "real-estate",
    name: "عقارات",
    description: "عقارات للبيع والإيجار في جميع المدن اليمنية",
    icon: "🏠",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&h=400&fit=crop",
    productCount: 342,
    subcategories: [
      { slug: "apartments", name: "شقق", icon: "🏢", productCount: 120 },
      { slug: "villas", name: "فلل", icon: "🏡", productCount: 65 },
      { slug: "lands", name: "أراضي", icon: "🏞️", productCount: 85 },
      { slug: "shops", name: "محلات تجارية", icon: "🏪", productCount: 42 },
      { slug: "offices", name: "مكاتب", icon: "🏬", productCount: 30 },
    ],
  },
  {
    slug: "food",
    name: "مواد غذائية",
    description: "جميع المواد الغذائية الطازجة والمعلبة",
    icon: "🍎",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&h=400&fit=crop",
    productCount: 567,
    subcategories: [
      { slug: "fruits-vegetables", name: "فواكه وخضروات", icon: "🥬", productCount: 85 },
      { slug: "meat-fish", name: "لحوم وأسماك", icon: "🥩", productCount: 65 },
      { slug: "dairy", name: "ألبان وأجبان", icon: "🧀", productCount: 78 },
      { slug: "canned", name: "معلبات", icon: "🥫", productCount: 120 },
      { slug: "beverages", name: "مشروبات", icon: "🥤", productCount: 95 },
      { slug: "spices", name: "بهارات وتوابل", icon: "🌶️", productCount: 65 },
      { slug: "sweets", name: "حلويات", icon: "🍫", productCount: 59 },
    ],
  },
  {
    slug: "home-appliances",
    name: "أدوات منزلية",
    description: "أدوات ومعدات منزلية حديثة وعالية الجودة",
    icon: "🏠",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=400&fit=crop",
    productCount: 423,
    subcategories: [
      { slug: "kitchen", name: "مطبخ", icon: "🍳", productCount: 120 },
      { slug: "cleaning", name: "تنظيف", icon: "🧹", productCount: 85 },
      { slug: "bathroom", name: "حمام", icon: "🚿", productCount: 65 },
      { slug: "lighting", name: "إضاءة", icon: "💡", productCount: 78 },
      { slug: "storage", name: "تخزين", icon: "📦", productCount: 45 },
      { slug: "furniture", name: "أثاث", icon: "🛋️", productCount: 30 },
    ],
  },
  {
    slug: "services",
    name: "خدمات ومهن",
    description: "خدمات متنوعة وفرص عمل في جميع التخصصات",
    icon: "💼",
    image: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=600&h=400&fit=crop",
    productCount: 189,
    subcategories: [
      { slug: "engineering", name: "هندسة", icon: "👷", productCount: 35 },
      { slug: "medical", name: "طب وتمريض", icon: "👨‍⚕️", productCount: 28 },
      { slug: "teaching", name: "تعليم وتدريس", icon: "👨‍🏫", productCount: 22 },
      { slug: "it", name: "تقنية معلومات", icon: "💻", productCount: 45 },
      { slug: "accounting", name: "محاسبة ومالية", icon: "📊", productCount: 20 },
      { slug: "driving", name: "قيادة وتوصيل", icon: "🚗", productCount: 15 },
      { slug: "sales", name: "مبيعات وتسويق", icon: "🛒", productCount: 24 },
      { slug: "plumbing", name: "سباكة وصيانة", icon: "🔧", productCount: 18 },
      { slug: "electrician", name: "كهرباء", icon: "⚡", productCount: 15 },
      { slug: "carpentry", name: "نجارة", icon: "🪚", productCount: 12 },
      { slug: "painting", name: "دهانات", icon: "🎨", productCount: 10 },
      { slug: "cleaning", name: "تنظيف منازل", icon: "🧹", productCount: 20 },
      { slug: "gardening", name: "تنسيق حدائق", icon: "🌿", productCount: 8 },
      { slug: "security", name: "حراسة وأمن", icon: "🛡️", productCount: 12 },
      { slug: "cooking", name: "طبخ وضيافة", icon: "👨‍🍳", productCount: 15 },
      { slug: "photography", name: "تصوير فوتوغرافي", icon: "📸", productCount: 10 },
      { slug: "translation", name: "ترجمة", icon: "🌐", productCount: 8 },
      { slug: "design", name: "تصميم جرافيك", icon: "🎨", productCount: 18 },
      { slug: "tutoring", name: "دروس خصوصية", icon: "📚", productCount: 25 },
      { slug: "moving", name: "نقل أثاث", icon: "🚚", productCount: 12 },
    ],
  },
];
